name: Nimarket
description: "Sebuah Aplikasi Market Mobile Untuk Kawasan Universitas Negeri Manado."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  permission_handler: ^11.3.0
  supabase_flutter: ^2.10.3
  device_info_plus: ^12.2.0
  mime: ^2.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/nimarket logo.png"